{
  parserClass="org.reviewPlugin.parser.ReviewParser"

  extends="com.intellij.extapi.psi.ASTWrapperPsiElement"

  psiClassPrefix="Review"
  psiImplClassSuffix="Impl"
  psiPackage="org.reviewPlugin.psi"
  psiImplPackage="org.reviewPlugin.psi.impl"

  elementTypeHolderClass="org.reviewPlugin.psi.ReviewTypes"
  elementTypeClass="org.reviewPlugin.psi.ReviewElementType"
  tokenTypeClass="org.reviewPlugin.psi.ReviewTokenType"

  psiImplUtilClass="org.reviewPlugin.psi.impl.ReviewPsiImplUtil"
}

reviewFile ::= item_*

private item_ ::= (property|COMMENT|CRLF)

property ::= (KEY? SEPARATOR VALUE?) | KEY {methods=[getKey getValue]}
